import React, { useEffect, useState } from 'react';
import { Bell, Building2, CheckCircle2, ClipboardCheck, Loader2, LockKeyhole, Save, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { db } from '../../lib/firebase';

type Settings = { institutionName: string; supportEmail: string; timezone: string; academicYear: string; allowSelfRegistration: boolean; requireAccountApproval: boolean; guardianReportsEnabled: boolean; requireTeacherRemarks: boolean; emailNotifications: boolean; guardianProgressEmails: boolean; wearableConsentRequired: boolean; deviceDataRetentionDays: number; };
const defaults: Settings = { institutionName: 'AIES', supportEmail: '', timezone: 'Africa/Nairobi', academicYear: '2026', allowSelfRegistration: true, requireAccountApproval: false, guardianReportsEnabled: true, requireTeacherRemarks: false, emailNotifications: true, guardianProgressEmails: true, wearableConsentRequired: true, deviceDataRetentionDays: 90 };

export default function AdminSettings() {
  const [settings, setSettings] = useState<Settings>(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [savedAt, setSavedAt] = useState<string | null>(null); const [error, setError] = useState('');
  useEffect(() => onSnapshot(doc(db, 'systemSettings', 'platform'), snapshot => { setSettings({ ...defaults, ...(snapshot.exists() ? snapshot.data() : {}) } as Settings); setLoading(false); }, () => { setError('Settings could not be loaded. Check your administrator permissions.'); setLoading(false); }), []);
  const set = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(current => ({ ...current, [key]: value }));
  const save = async () => { setError(''); setSaving(true); try { await setDoc(doc(db, 'systemSettings', 'platform'), { ...settings, updatedAt: new Date().toISOString() }, { merge: true }); setSavedAt(new Date().toLocaleTimeString()); } catch { setError('Settings were not saved. Check your connection and administrator permissions.'); } finally { setSaving(false); } };
  if (loading) return <div className="min-h-[40vh] flex items-center justify-center text-neutral-500"><Loader2 className="w-5 h-5 animate-spin mr-2" />Loading system settings...</div>;
  return <div className="max-w-5xl space-y-6 pb-12"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><p className="text-sm font-bold text-purple-700 uppercase tracking-wider">Administration</p><h1 className="text-3xl font-bold text-neutral-900 mt-1">System settings</h1><p className="text-neutral-500 mt-2">Manage platform-wide defaults. Changes apply to new activity and do not modify existing learner records.</p></div><button onClick={save} disabled={saving} className="px-5 py-3 bg-purple-600 text-white font-bold rounded-xl hover:bg-purple-700 disabled:opacity-50"><Save className="inline w-4 h-4 mr-2" />{saving ? 'Saving...' : 'Save changes'}</button></div>{error && <div className="p-4 rounded-xl bg-red-50 text-red-700 border border-red-200">{error}</div>}{savedAt && <div className="p-3 rounded-xl bg-emerald-50 text-emerald-700 border border-emerald-200 flex items-center gap-2"><CheckCircle2 className="w-4 h-4" />Saved at {savedAt}.</div>}
    <SettingsCard icon={<Building2 className="w-5 h-5" />} title="Institution profile" description="Displayed in administrative and guardian-facing reports."><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Institution name"><input value={settings.institutionName} onChange={event => set('institutionName', event.target.value)} className="settings-input" /></Field><Field label="Support email"><input type="email" value={settings.supportEmail} onChange={event => set('supportEmail', event.target.value)} placeholder="support@example.edu" className="settings-input" /></Field><Field label="Academic year"><input value={settings.academicYear} onChange={event => set('academicYear', event.target.value)} className="settings-input" /></Field><Field label="Timezone"><select value={settings.timezone} onChange={event => set('timezone', event.target.value)} className="settings-input"><option>Africa/Nairobi</option><option>UTC</option><option>Europe/London</option><option>America/New_York</option></select></Field></div></SettingsCard>
    <SettingsCard icon={<SlidersHorizontal className="w-5 h-5" />} title="Accounts and access" description="Choose how new learners and guardians enter the platform."><Toggle label="Allow self-registration" description="Let users create their own student, teacher, or guardian account." checked={settings.allowSelfRegistration} onChange={value => set('allowSelfRegistration', value)} /><Toggle label="Require account approval" description="Mark new accounts for administrator review before institutional access is granted." checked={settings.requireAccountApproval} onChange={value => set('requireAccountApproval', value)} /></SettingsCard>
    <SettingsCard icon={<ClipboardCheck className="w-5 h-5" />} title="Guardian reports" description="Controls for the evidence-based report shared with parents and guardians."><Toggle label="Enable guardian reports" description="Allow linked guardians to open and generate student reports." checked={settings.guardianReportsEnabled} onChange={value => set('guardianReportsEnabled', value)} /><Toggle label="Require teacher remarks before export" description="Use this as an administrative policy flag when reviewing report readiness." checked={settings.requireTeacherRemarks} onChange={value => set('requireTeacherRemarks', value)} /></SettingsCard>
    <SettingsCard icon={<Bell className="w-5 h-5" />} title="Notifications" description="Set the default communication channels for new accounts."><Toggle label="Enable email notifications" description="Allow platform email notifications where email delivery is configured." checked={settings.emailNotifications} onChange={value => set('emailNotifications', value)} /><Toggle label="Guardian progress emails" description="Permit scheduled progress-update emails to linked guardians." checked={settings.guardianProgressEmails} onChange={value => set('guardianProgressEmails', value)} /></SettingsCard>
    <SettingsCard icon={<ShieldCheck className="w-5 h-5" />} title="Privacy and wearable data" description="Protect learner data and make sensor limits clear."><Toggle label="Require wearable consent" description="Require consent before a learner connects a Bluetooth wearable." checked={settings.wearableConsentRequired} onChange={value => set('wearableConsentRequired', value)} /><Field label="Device-data retention (days)"><input type="number" min="1" max="3650" value={settings.deviceDataRetentionDays} onChange={event => set('deviceDataRetentionDays', Math.max(1, Number(event.target.value) || 1))} className="settings-input max-w-xs" /><p className="mt-2 text-sm text-neutral-500">Retention is a policy setting. Automated deletion must be configured in a secure backend job before historical data is removed.</p></Field><div className="mt-5 p-4 bg-amber-50 border border-amber-200 rounded-xl text-sm text-amber-900 flex gap-3"><LockKeyhole className="w-5 h-5 flex-none" /><p>Wearable data must not be used to diagnose medical conditions or label a learner as attentive, inattentive, or fatigued.</p></div></SettingsCard>
  </div>;
}
function SettingsCard({ icon, title, description, children }: { icon: React.ReactNode; title: string; description: string; children: React.ReactNode }) { return <section className="bg-white rounded-2xl border border-neutral-200 shadow-sm overflow-hidden"><div className="p-6 border-b border-neutral-100 flex gap-3"><div className="w-10 h-10 bg-purple-50 text-purple-700 rounded-xl flex items-center justify-center">{icon}</div><div><h2 className="font-bold text-neutral-900">{title}</h2><p className="text-sm text-neutral-500 mt-1">{description}</p></div></div><div className="p-6 space-y-5">{children}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-neutral-700">{label}<div className="mt-2">{children}</div></label>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-start justify-between gap-5"><div><p className="font-semibold text-neutral-800">{label}</p><p className="text-sm text-neutral-500 mt-1">{description}</p></div><button type="button" onClick={() => onChange(!checked)} className={`relative flex-none w-12 h-7 rounded-full transition-colors ${checked ? 'bg-purple-600' : 'bg-neutral-300'}`} aria-pressed={checked}><span className={`absolute top-1 w-5 h-5 rounded-full bg-white shadow transition-transform ${checked ? 'translate-x-6' : 'translate-x-1'}`} /></button></div>; }
